# fly.toml app configuration file generated for koosbot on 2023-05-25T21:06:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "koosbot"
primary_region = "sea"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
