# fly.toml app configuration file generated for koosbot on 2023-10-13T00:30:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "koosbot"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
