name: "Push Docker Images"

on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "prisma/**"
            - ".github/**"
            - "Dockerfile"
            - "Dockerfile.alpine"
    workflow_dispatch:

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Get version
              id: version
              run: |
                  echo "koosbot_version=$(jq .version package.json -r)" >> $GITHUB_OUTPUT

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Step to build and push the default Docker image (non-Alpine)
            - name: Build and Push Docker Image (default)
              uses: docker/build-push-action@v3
              with:
                  push: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/${{ github.repository }}:latest
                      ghcr.io/${{ github.repository }}:${{ steps.version.outputs.koosbot_version }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            # Step to build and push the Alpine Docker image
            - name: Build and Push Docker Image (Alpine)
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile.alpine # Specify the Alpine Dockerfile
                  push: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/${{ github.repository }}:alpine
                      ghcr.io/${{ github.repository }}:alpine-${{ steps.version.outputs.koosbot_version }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
