name: "Push Docker Images"

on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "server/**"
            - "prisma/**"
            - ".github/**"
            - "Dockerfile"
    workflow_dispatch:

jobs:
    push-to-registry:
        name: Push Image to Forgejo Packages
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Get version
              id: version
              run: |
                  echo "koosbot_version=$(jq .version package.json -r)" >> $GITHUB_OUTPUT

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ujol.dev
                  username: ${{ secrets.FORGEJO_USER }}
                  password: ${{ secrets.FORGEJO_PASSWORD }}

            - name: Build Docker Image
              uses: docker/build-push-action@v3
              with:
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: |
                      ujol.dev/u/koosbot:latest
                      ujol.dev/u/koosbot:latest-${{ steps.version.outputs.koosbot_version }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
